remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

title: "LightDock"
title_separator: "|"
site.description: "A flexible multi-scale protein docking framework"
repository: "brianjimenez/lightdock"
logo: "/assets/images/luciferin_88x88.png"

include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

